name: Trial of the Crusader raid report
description: File a PTR test raid report
title: "[PTR Raid report - Trial of the Crusader]: YOUR_GUILD_NAME_HERE"
labels: ["raid", "PTR", "trial of the crusader"]
projects: ["master"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this raid report!
  - type: textarea
    id: t-mech
    attributes:
      label: Mechanics comments on trash mobs
      description: Give us your overall comments on the mechanics that trash had. Make sure to mention spells that are broken, linked packs missing, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: t-tune
    attributes:
      label: Tuning comments on trash mobs
      description: Give us your overall comments on the tuning that trash had. Make sure to mention what spells can be nerfed/buffed
      placeholder: Tell us what you see!
    validations:
      required: false

  ###################################################
  #                      BOSSES                     #
  ###################################################

  - type: textarea
  - type: textarea
    id: boss-mech-beasts
    attributes:
      label: Mechanics comments on The Beasts of Northrend
      description: Give us your overall comments on the mechanics that the encounter had. Make sure to mention Gormok add behaviour, Jormungar poison/paralytic issues, Icehowl charge mechanics, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: boss-mech-jaraxxus
    attributes:
      label: Mechanics comments on Lord Jaraxxus
      description: Give us your overall comments on the mechanics that Lord Jaraxxus had. Make sure to mention portal/volcano spawning, add behaviour, incinerate flesh, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: boss-mech-faction-champs
    attributes:
      label: Mechanics comments on Faction Champions
      description: Give us your overall comments on the mechanics that Faction Champions had. Make sure to mention AI behaviour, CC interactions, healing/damage patterns, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: boss-mech-twins
    attributes:
      label: Mechanics comments on Twin Val'kyr
      description: Give us your overall comments on the mechanics that Twin Val'kyr had. Make sure to mention orb behaviour, light/dark essence interactions, shield mechanics, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: boss-mech-anub
    attributes:
      label: Mechanics comments on Anub'arak
      description: Give us your overall comments on the mechanics that Anub'arak had. Make sure to mention burrowing behaviour, add spawns, penetrating cold, hard mode leech, etc.
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
  - type: textarea
    id: overall-mech
    attributes:
      label: Overall comments on raid mechanics
      description: The state of the raid when it comes to bugs and other weird things happening
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
  - type: dropdown
    id: overall-mech-drop
    attributes:
      label: Give a rating out of 10 for the state of the mechanics in the raid
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
  - type: textarea
    id: overall-tune
    attributes:
      label: Overall comments on tuning
      description: The state of the raid when it comes to tuning
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
  - type: dropdown
    id: overall-tune-drop
    attributes:
      label: Give a rating out of 10 for the state of the tuning in the raid
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
